<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<PackageType>Template</PackageType>
		<PackageVersion>1.0.1</PackageVersion>
		<PackageId>DotNetCoreWebApiTemplate</PackageId>
		<Title>DotNetCore Web API Template</Title>
		<Authors>Manish Kumar</Authors>
		<Description>A dotnet new template for quickly scaffolding ASP.NET Core Web API projects, with options to include only the features you need. After generating the project, optionally run 'dotnet new sln' followed by 'dotnet sln add YourProjectName.csproj' to create a solution file (not required to build or run the project).</Description>
		<PackageTags>dotnet-new;templates;webapi;aspnetcore</PackageTags>
		<PackageProjectUrl>https://github.com/manishkumar2511/DotNetCoreWebApiTemplate</PackageProjectUrl>
		<RepositoryUrl>https://github.com/manishkumar2511/DotNetCoreWebApiTemplate</RepositoryUrl>
		<IncludeContentInPack>true</IncludeContentInPack>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<ContentTargetFolders>content</ContentTargetFolders>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<NoWarn>NU5128</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="..\DotNetCoreWebApiTemplate\**\*"
				 Exclude="..\DotNetCoreWebApiTemplate\**\bin\**;..\DotNetCoreWebApiTemplate\**\obj\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>